# Generated by Django 5.2.13 on 2026-05-10 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_quizattemptanswer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizattemptanswer',
            new_name='school_quiz_attempt_8a2497_idx',
            old_name='school_quiz_attempt_a155f0_idx',
        ),
        migrations.AlterField(
            model_name='quizattemptanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
