# Generated by Django 5.2.13 on 2026-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_school_quiz_attempt_a155f0_idx_school_quiz_attempt_8a2497_idx_and_more'),
        ('school', '0006_studentinvitation'),
    ]

    operations = [
    ]
